### ISSUE TITLE
The "Confirm Learning" option does not work.

### ISSUE THREAD

**Issue by chkmyid** [Lethay/TalentedClassic#26]
When the "Confirm Learning" option is checked, clicking to learn the attributes will cause no response. This option is used to determine the talent of your choice so that you do not make any mistakes when you attempt to learn talent hastily. This has not worked properly since the 191007 date patch. I had to uncheck the option "Confirm Learning" to learn talent.
This is just a confirmation frame before learning talent. Are you modifying it?

**Comment by Lethay** [comment]
Yes, I know what that option is. I modified it on the 191007 patch as part of a fix to the Apply button.
interestingly, it works for me. Do you get no LUA error?  And the yes / no box doesn't appear?

**Comment by Lethay** [comment]
I added some debug printing. First screenshot shows what happens when I click normally with Confirm Learning checked:
![1](https://user-images.githubusercontent.com/5658454/66632083-988bd700-ebff-11e9-9188-5b0649d443e2.png)

Just for extra debugging, I disabled it checking whether I have enough talent points ('cos I have zero), and as you can see, everything works:
![2](https://user-images.githubusercontent.com/5658454/66632154-be18e080-ebff-11e9-9929-c6ad4cabc85c.png)

So, ¯\_(ツ)_/¯

**Comment by Lethay** [comment]
As for the change in 191007,

https://github.com/Lethay/TalentedClassic/commit/f3927daee062cca4ccedb7241dd7a85fb0086058#diff-388a20dda4464ddb0a92bf5941284b1b

```

****+	--Create confirmation dialogue**
+	local info = self:GetTalentInfo(self.current.class)
+	if not info then return end
+	local talent = info[tab].talents[index]**

	ShowDialog(L["Are you sure that you want to learn \"%s (%d/%d)\" ?"]:format(
-			self:GetTalentName(template.class, tab, index),
+			talent.info.name,
			template[tab][index] + 1,
-			self:GetTalentRanks(template.class, tab, index)),
+			talent.info.ranks),
		tab, index)
```

**Comment by Lethay** [comment]
Managed to get some time to play the day before yesterday and levelled up. The buttons work just fine with and without "Confirm Learning" active. Are you sure you had the most recent version?

**Comment by chkmyid** [comment]
I installed the updated 191011, but I don't have time to test it yet.
